### ISSUE TITLE
Arduino IDE will not start with GamerArduinoTools installed

### ISSUE THREAD

**Issue by aerger** [techwillsaveus/GamerArduinoTools#1]
I have unzipped the tools directory into the \My Documents\Arduino\ folder (Windows 7). Once I've done this, the Arduino IDE will not complete loading: the splash screen appears to be loading the IDE application, but the application itself never shows. 

Checking Task Manager, Arduino IDE executable is not listed, so it appears it is not hanging, but failing silently.

If I remove the GamerArduinoTools folders from the tools folder, the Arduino IDE starts up normally. I have tried removing one of the two GATools folders to see if the problem is only one of the two folders/tools, but it made no difference. Both have to be removed to restore the Arduino software's ability to fully load.

I'm running Arduino IDE version 1.8.5 (running on Windows 7, again) and trying to load the currently-available-here GamerArduinoTools. 
 
I suspect these tools were written for an earlier version of the Arduino IDE software, but it's only a guess.  Any help appreciated.

**Comment by josephphayden** [comment]
Hey @aerger, thanks for getting in touch.

This is an old repo which we no longer support I'm afraid (I'll be taking it down shortly). We've moved this functionality online onto our Make platform, along with our other Gamer resources, as it provides a better experience for users.

If you visit the [Gamer Page](https://make.techwillsaveus.com/gamer-kit/) you can then click `+ New animation` in the top right corner to get to the animation generator. Here you can use the UI to generate images/animations and export the code for the Arduino IDE.

Sorry for your wasted time. Hope you enjoy the animation generator! Let me know if you need any further help.

**Comment by aerger** [comment]
Thanks for quick reply and redirect to the tool on your site. I'll check it out.

**Comment by josephphayden** [comment]
Ok, cheers!
